[versions]

lightweightcharts-code = "16"
lightweightcharts = "4.0.0"
sdk-min = "23"
sdk-compile = "36"

android-gradle = "8.13.0"
kotlin = "2.2.21"
google-services = "4.4.4"
firebase-crashlytics = "3.0.6"
arturbosch-detekt = "1.23.1"

firebase-bom = "34.5.0"
appcompat = "1.7.1"
core-ktx = "1.17.0"
constraintlayout = "2.2.1"
material = "1.13.0"
coroutines = "1.10.2"
lifecycle = "2.9.4"
permissionsdispatcher = "4.9.2"

webkit = "1.14.0"
gson = "2.13.2"

[libraries]

tradingview-lightweightcharts = { module = "com.tradingview:lightweightcharts", version.ref = "lightweightcharts" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-material = { module = "com.google.android.material:material", version.ref = "material" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

permissionsdispatcher = { module = "com.github.permissions-dispatcher:permissionsdispatcher", version.ref = "permissionsdispatcher" }
permissionsdispatcher-processor = { module = "com.github.permissions-dispatcher:permissionsdispatcher-processor", version.ref = "permissionsdispatcher" }

androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "arturbosch-detekt" }

[plugins]


android = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
maven-publish = { id = "maven-publish" }

arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "arturbosch-detekt" }
